export const courses = {
  data() {
    return {
      options1: [
        { credit: null, value: null, text: "Please select an option" },
        { credit: 3, value: 1, text: "ENG-MATHS 1" },
        { credit: 4, value: 2, text: "c programming" },
        { credit: 3, value: 3, text: "python" },
        { credit: 3, value: 4, text: "DHV" },
        { credit: 3, value: 5, text: "ENG-maths 2" },
        { credit: 4, value: 6, text: "Data Structure using C" },
        { credit: 5, value: 7, text: "Digital Electronics" },
        { credit: 4, value: 8, text: "Basic Electronics" },
        { credit: 1, value: 9, text: "workshop" },
        { credit: 1, value: 10, text: "Engineering Graphics" },
        { credit: 3, value: 11, text: "Professional Communication" },
        { credit: 4, value: 12, text: "Engineering Physics" },
        { credit: 1, value: 13, text: "Intro to computer science Engineering" },
        { credit: 1, value: 14, text: "Language Lab" },
      ],
      options2: [
        { credit: null, value: null, text: "Please select an option" },
        { credit: 3, value: 1, text: "Engineering Mathematics-I" },
        { credit: 4, value: 2, text: "Basic Electrical Engg" },
        { credit: 4, value: 3, text: "Basic Electronics" },
        { credit: 4, value: 4, text: "Engineering Physics" },
        { credit: 4, value: 5, text: "Introduction to ‘C’ " },
        { credit: 3, value: 6, text: "Communication Skills" },
        { credit: 1, value: 7, text: "Intro to Electronics" },
        { credit: 1, value: 8, text: "Engineering Workshop" },
        { credit: 3, value: 9, text: "Engineering Mathematics-II" },
        { credit: 2, value: 10, text: "Engineering Graphics" },
        { credit: 3, value: 11, text: "PYTHON-I" },
        { credit: 5, value: 12, text: "Electronic Circuits and simulation" },
        { credit: 4, value: 13, text: "Network Analysis and Synthesis" },
        { credit: 3, value: 14, text: "Discourse of human values" },
        { credit: 1, value: 15, text: "Language Lab" },
      ],
    };
  },
};
